### ISSUE TITLE
Support incremental builds

### ISSUE THREAD

**Issue by ptylr** [Crownpeak/gatsby-source-crownpeak-dxm#1]
Support incremental data fetching (Has the ability to create, update, and delete data based on CMS content changes).

Incremental data fetching is a critical part of keeping build times blazing fast. In Gatsby Cloud we expect first-class plugins to be able to drive <5 second Preview updates and <10 second Incremental Builds on a site with 8192 pages. These metrics are measured by Willit.build benchmarks which will be discussed below.

**Comment by richard-lund** [comment]
Delivered in version 1.1.0, 2021-03-16.
